name = "SpeciesDistributionToolkit"
uuid = "72b53823-5c0b-4575-ad0e-8e97227ad13b"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>"]
version = "1.6.3"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Fauxcurrences = "a2d61402-033a-4ca9-aef4-652d70cf7c9c"
GBIF = "ee291a33-5a6c-5552-a3c8-0f29a1181037"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
OccurrencesInterface = "ee6415c8-122a-4855-89a1-90f4bac06ba6"
Phylopic = "c889285c-44aa-4473-b1e1-56f5d4e3ccf5"
PolygonOps = "647866c9-e3ac-4575-94e7-e3d426903924"
PseudoAbsences = "68905d83-288d-4570-b05e-f7eb6299ad2c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SDeMo = "3e5feb82-bcca-434d-9cd5-c11731a21467"
SimpleSDMDatasets = "2c7d61d0-5c73-410d-85b2-d2e7fbbdcefa"
SimpleSDMLayers = "2c645270-77db-11e9-22c3-0f302a89c64c"
SimpleSDMPolygons = "dd4c243c-bc7b-45f6-b2b3-6bd128d3a12b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
ZipArchives = "49080126-0e18-4c2a-b176-c102e4b3760c"

[weakdeps]
STAC = "08e62803-e111-4f53-be9b-274ff296e9da"
SpatialBoundaries = "8d2ba62a-3d23-4a2b-b692-6b63e9267be2"

[extensions]
STACExt = "STAC"
SpatialBoundariesExt = "SpatialBoundaries"

[compat]
Distances = "0.10"
Downloads = "1"
Fauxcurrences = "1"
GBIF = "1"
GeoJSON = "0.8"
HTTP = "1.10"
OccurrencesInterface = "1"
Phylopic = "1"
PolygonOps = "0.1"
PseudoAbsences = "1"
Reexport = "1.2"
SDeMo = "1"
STAC = "0.1"
SimpleSDMDatasets = "1"
SimpleSDMLayers = "1"
SimpleSDMPolygons = "1"
SpatialBoundaries = "0.2"
StatsBase = "0.34"
TestItems = "1"
ZipArchives = "2.4"
julia = "1.10"
