name = "SpeciesDistributionToolkit"
uuid = "72b53823-5c0b-4575-ad0e-8e97227ad13b"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>"]
version = "0.1.3"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Fauxcurrences = "a2d61402-033a-4ca9-aef4-652d70cf7c9c"
GBIF = "ee291a33-5a6c-5552-a3c8-0f29a1181037"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
OccurrencesInterface = "ee6415c8-122a-4855-89a1-90f4bac06ba6"
Phylopic = "c889285c-44aa-4473-b1e1-56f5d4e3ccf5"
PolygonOps = "647866c9-e3ac-4575-94e7-e3d426903924"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SDeMo = "3e5feb82-bcca-434d-9cd5-c11731a21467"
SimpleSDMDatasets = "2c7d61d0-5c73-410d-85b2-d2e7fbbdcefa"
SimpleSDMLayers = "2c645270-77db-11e9-22c3-0f302a89c64c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
Distances = "0.10"
Downloads = "1"
Fauxcurrences = "0"
GBIF = "0.4"
GeoJSON = "0.8"
MakieCore = "0.8"
Phylopic = "0"
PolygonOps = "0.1"
Reexport = "1.2"
SDeMo = "0"
SimpleSDMDatasets = "0"
SimpleSDMLayers = "1"
StatsBase = "0.34"
TestItems = "1"
ZipFile = "0.10"
julia = "1.8"
