name = "SimpleSDMLayers"
uuid = "2c645270-77db-11e9-22c3-0f302a89c64c"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>", "Gabriel Dansereau <gabriel.dansereau@umontreal.ca>"]
version = "1.2.2"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[weakdeps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NeutralLandscapes = "71847384-8354-4223-ac08-659a5128069f"


[extensions]
ClusteringExtension = "Clustering"
MakieExtension = "MakieCore"
MultivariateStatsExtension = "MultivariateStats"
NeutralLandscapesExtension = "NeutralLandscapes"

[compat]
ArchGDAL = "0.10"
Clustering = "0.15"
Distances = "0.10"
MakieCore = "0.9"
MultivariateStats = "0.10"
NeutralLandscapes = "0.1"
Proj = "1"
Statistics = "1"
StatsBase = "0.34"
Tables = "1"
TestItems = "1"
julia = "1.10"
