name = "SimpleSDMLayers"
uuid = "2c645270-77db-11e9-22c3-0f302a89c64c"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>", "Gabriel Dansereau <gabriel.dansereau@umontreal.ca>"]
version = "0.9.5"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
PolygonOps = "647866c9-e3ac-4575-94e7-e3d426903924"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Distances = "0.10"
GeometryBasics = "0.4"
OffsetArrays = "1.12"
PolygonOps = "0.1"
StatsBase = "0.33, 0.34"
Tables = "1"
julia = "1.8"
