name = "SimpleSDMLayers"
uuid = "2c645270-77db-11e9-22c3-0f302a89c64c"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>", "Gabriel Dansereau <gabriel.dansereau@umontreal.ca>"]
version = "1.2.0"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[extensions]
ClusteringExtension = "Clustering"
NeutralLandscapesExtension = "NeutralLandscapes"

[weakdeps]
Clustering="aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
NeutralLandscapes="71847384-8354-4223-ac08-659a5128069f"

[compat]
ArchGDAL = "0.10"
Clustering = "0.15"
Distances = "0.10"
NeutralLandscapes = "0.1"
Proj = "1"
Requires = "1.3"
Statistics = "1"
StatsBase = "0.34"
TestItems = "1"
Tables = "1"
julia = "1.10"
