name = "GBIF"
uuid = "ee291a33-5a6c-5552-a3c8-0f29a1181037"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>"]
version = "1.1.1"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OccurrencesInterface = "ee6415c8-122a-4855-89a1-90f4bac06ba6"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
ZipArchives = "49080126-0e18-4c2a-b176-c102e4b3760c"

[compat]
Base64 = "1"
CSV = "0.10"
HTTP = "1"
JSON = "0.21"
OccurrencesInterface = "1"
Tables = "1.10"
ZipArchives = "2.4"
julia = "1.8"
