name = "GBIF"
uuid = "ee291a33-5a6c-5552-a3c8-0f29a1181037"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>"]
version = "1.0.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OccurrencesInterface = "ee6415c8-122a-4855-89a1-90f4bac06ba6"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
HTTP = "1"
JSON = "0.21"
OccurrencesInterface = "1"
Tables = "1.10"
julia = "1.8"
