name = "Phylopic"
uuid = "c889285c-44aa-4473-b1e1-56f5d4e3ccf5"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
