name = "Phylopic"
uuid = "c889285c-44aa-4473-b1e1-56f5d4e3ccf5"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>"]
version = "1.0.1"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
MakieExtension = "Makie"

[compat]
Downloads = "1.6"
FileIO = "1.17"
HTTP = "1"
JSON = "0.21"
Makie = "0.21 - 0.23"
TestItems = "1"
julia = "1.8"
