name = "OccurrencesInterface"
uuid = "ee6415c8-122a-4855-89a1-90f4bac06ba6"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>"]
version = "1.2.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
MakieExtension = "Makie"

[compat]
Dates = "1"
JSON = "0.21, 1"
Makie = "0.21 - 0.24"
Tables = "1"
TestItems = "1"
julia = "^1.8"
