name = "SimpleSDMDatasets"
uuid = "2c7d61d0-5c73-410d-85b2-d2e7fbbdcefa"
version = "1.0.3"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
ZipArchives = "49080126-0e18-4c2a-b176-c102e4b3760c"

[compat]
Downloads = "1"
NetCDF = "0.12"
TestItems = "1.0.0"
ZipArchives = "2.4"
julia = "1.8"
