name = "Fauxcurrences"
uuid = "a2d61402-033a-4ca9-aef4-652d70cf7c9c"
authors = ["Timoth√©e Poisot <timothee.poisot@umontreal.ca>"]
version = "0.1.1"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
GBIF = "ee291a33-5a6c-5552-a3c8-0f29a1181037"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SimpleSDMLayers = "2c645270-77db-11e9-22c3-0f302a89c64c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distances = "0.10"
GBIF = "^0.4"
SimpleSDMLayers = "0.9"
StatsBase = "0.33"
julia = "1.8"
