[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NeutralLandscapes = "71847384-8354-4223-ac08-659a5128069f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
STAC = "08e62803-e111-4f53-be9b-274ff296e9da"
SpatialBoundaries = "8d2ba62a-3d23-4a2b-b692-6b63e9267be2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DocumenterVitepress = "0.1"
